package se.umu.chlu0125.inscriber.models;

import android.location.LocationManager;

import java.io.Serializable;


/**
 * @author: Christoffer Lundstrom
 * @date: 08/08/2019
 * <p>
 * Description: A model describing a Location with Lat and Long coordinates.
 * This class is used to circumvent a problem with reading Android-location objects from firebase
 * database. Instantiating objects from firebase requires a no-parameter constructor which Android does not supply.
 *
 */
public class Location implements Serializable {

    private double mLatitude;
    private double mLongitude;

    public Location (){
    }

    /**
     * Get the latitude, in degrees.
     *
     * <p>All locations generated by the {@link LocationManager}
     * will have a valid latitude.
     */
    public double getLatitude() {
        return mLatitude;
    }

    /**
     * Set the latitude, in degrees.
     */
    public void setLatitude(double latitude) {
        mLatitude = latitude;
    }

    /**
     * Get the longitude, in degrees.
     *
     * <p>All locations generated by the {@link LocationManager}
     * will have a valid longitude.
     */
    public double getLongitude() {
        return mLongitude;
    }

    /**
     * Set the longitude, in degrees.
     */
    public void setLongitude(double longitude) {
        mLongitude = longitude;
    }

}
